--- crates/livekit_client/Cargo.toml.orig	2024-12-28 09:16:57 UTC
+++ crates/livekit_client/Cargo.toml
@@ -43,7 +43,7 @@ image.workspace = true
 smallvec.workspace = true
 image.workspace = true
 
-[target.'cfg(not(target_os = "windows"))'.dependencies]
+[target.'cfg(not(any(target_os = "windows", target_os = "freebsd")))'.dependencies]
 livekit.workspace = true
 
 [target.'cfg(target_os = "macos")'.dependencies]
