--- crates/zed/Cargo.toml.orig	2024-10-24 17:42:16 UTC
+++ crates/zed/Cargo.toml
@@ -123,7 +123,7 @@ winresource = "0.1"
 [target.'cfg(target_os = "windows")'.build-dependencies]
 winresource = "0.1"
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 ashpd.workspace = true
 # We don't use zstd in the zed crate, but we want to add this feature when compiling a desktop build of Zed
 zstd = { workspace = true, features = [ "pkg-config" ] }
