--- crates/zed/Cargo.toml.orig	2024-09-04 14:30:20 UTC
+++ crates/zed/Cargo.toml
@@ -115,7 +115,7 @@ winresource = "0.1"
 [target.'cfg(target_os = "windows")'.build-dependencies]
 winresource = "0.1"
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 ashpd.workspace = true
 
 [dev-dependencies]
