--- crates/zed/Cargo.toml.orig	2024-07-19 19:12:05 UTC
+++ crates/zed/Cargo.toml
@@ -108,7 +108,7 @@ winresource = "0.1"
 [target.'cfg(target_os = "windows")'.build-dependencies]
 winresource = "0.1"
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 ashpd.workspace = true
 
 [dev-dependencies]
