--- crates/zed/Cargo.toml.orig	2024-08-27 11:06:16 UTC
+++ crates/zed/Cargo.toml
@@ -114,7 +114,7 @@ winresource = "0.1"
 [target.'cfg(target_os = "windows")'.build-dependencies]
 winresource = "0.1"
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 ashpd.workspace = true
 
 [dev-dependencies]
