--- crates/gpui/Cargo.toml.orig	2024-07-10 14:12:26 UTC
+++ crates/gpui/Cargo.toml
@@ -101,7 +101,7 @@ objc = "0.2"
 metal = "0.25"
 objc = "0.2"
 
-[target.'cfg(any(target_os = "linux", target_os = "windows"))'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd", target_os = "windows"))'.dependencies]
 flume = "0.11"
 blade-graphics.workspace = true
 blade-macros.workspace = true
@@ -109,7 +109,7 @@ cosmic-text = { git = "https://github.com/pop-os/cosmi
 bytemuck = "1"
 cosmic-text = { git = "https://github.com/pop-os/cosmic-text", rev = "542b20c" }
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 as-raw-xcb-connection = "1"
 ashpd.workspace = true
 calloop = "0.13.0"
