--- crates/cli/Cargo.toml.orig	2025-05-23 07:52:21 UTC
+++ crates/cli/Cargo.toml
@@ -24,7 +24,7 @@ collections.workspace = true
 anyhow.workspace = true
 clap.workspace = true
 collections.workspace = true
-ipc-channel = "0.19"
+ipc-channel = { git = "https://github.com/servo/ipc-channel.git", rev = "1e6db1c3396c18cb18ca29993bbd6fe9b3b9885d" }
 parking_lot.workspace = true
 paths.workspace = true
 release_channel.workspace = true
