--- crates/rpc/Cargo.toml.orig	2024-09-27 20:04:41 UTC
+++ crates/rpc/Cargo.toml
@@ -37,7 +37,7 @@ zstd = "0.11"
 util.workspace = true
 zstd = "0.11"
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 zstd = { version = "0.11", features = [ "pkg-config" ] }
 
 [dev-dependencies]
