--- crates/zed/Cargo.toml.orig	2024-07-31 16:17:45 UTC
+++ crates/zed/Cargo.toml
@@ -113,7 +113,7 @@ winresource = "0.1"
 [target.'cfg(target_os = "windows")'.build-dependencies]
 winresource = "0.1"
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 ashpd.workspace = true
 
 [dev-dependencies]
