--- crates/zed/Cargo.toml.orig	2024-10-02 15:03:39 UTC
+++ crates/zed/Cargo.toml
@@ -123,7 +123,7 @@ winresource = "0.1"
 [target.'cfg(target_os = "windows")'.build-dependencies]
 winresource = "0.1"
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 ashpd.workspace = true
 
 [dev-dependencies]
