--- crates/fs/Cargo.toml.orig	2024-09-04 14:30:20 UTC
+++ crates/fs/Cargo.toml
@@ -43,7 +43,7 @@ windows.workspace = true
 [target.'cfg(target_os = "windows")'.dependencies]
 windows.workspace = true
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 ashpd.workspace = true
 
 [dev-dependencies]
