--- crates/gpui/Cargo.toml.orig	2024-08-27 11:06:16 UTC
+++ crates/gpui/Cargo.toml
@@ -102,16 +102,16 @@ objc = "0.2"
 metal = "0.29"
 objc = "0.2"
 
-[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd", target_os = "macos"))'.dependencies]
 pathfinder_geometry = "0.5"
 
-[target.'cfg(any(target_os = "linux", target_os = "windows"))'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd", target_os = "windows"))'.dependencies]
 blade-graphics.workspace = true
 blade-macros.workspace = true
 blade-util.workspace = true
 bytemuck = "1"
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 as-raw-xcb-connection = "1"
 ashpd.workspace = true
 calloop = "0.13.0"
