--- crates/cli/Cargo.toml.orig	2025-08-03 07:08:44 UTC
+++ crates/cli/Cargo.toml
@@ -24,7 +24,7 @@ collections.workspace = true
 anyhow.workspace = true
 clap.workspace = true
 collections.workspace = true
-ipc-channel = "0.19"
+ipc-channel = "0.20.1"
 parking_lot.workspace = true
 paths.workspace = true
 release_channel.workspace = true
