--- crates/cli/Cargo.toml.orig	2025-05-22 12:47:07 UTC
+++ crates/cli/Cargo.toml
@@ -24,7 +24,6 @@ collections.workspace = true
 anyhow.workspace = true
 clap.workspace = true
 collections.workspace = true
-ipc-channel = "0.19"
 parking_lot.workspace = true
 paths.workspace = true
 release_channel.workspace = true
@@ -32,6 +31,12 @@ workspace-hack.workspace = true
 util.workspace = true
 tempfile.workspace = true
 workspace-hack.workspace = true
+
+[target.'cfg(not(target_os = "freebsd"))'.dependencies]
+ipc-channel = "0.19"
+
+[target.'cfg(target_os = "freebsd")'.dependencies]
+ipc-channel = { version = "0.19", features = ["force-inprocess"] }
 
 [target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 exec.workspace = true
